/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module.disruptor;

import org.mule.api.MuleEvent;
import org.mule.api.MuleMessage;
import org.mule.construct.Flow;
import org.mule.tck.FunctionalTestCase;
import org.mule.tck.AbstractMuleTestCase;

import org.junit.Test;

public class DisruptorModuleTest extends FunctionalTestCase {
    @Override
    protected String getConfigResources() {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception {

        long start = System.nanoTime();
        for (int i = 0; i < 10000; i++) {
            muleContext.getClient().dispatch("vm://in", "Foo", null);
            MuleMessage response = muleContext.getClient().request("vm://out", 15000);
            assertNotNull(response);
        }
        long duration = System.nanoTime() - start;
        logger.info("ELAPSED: " + (double) duration / 1000000000.0);
    }


}
