/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module.disruptor;

import org.mule.api.annotations.Module;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;

/**
 * Generic module
 *
 * @author MuleSoft, Inc.
 */
@Module(name="disruptor", schemaVersion="1.0-SNAPSHOT")
public class DisruptorModule
{
    /**
     * Configurable
     */
    @Configurable
    private String myProperty;

    /**
     * Set property
     *
     * @param myProperty My property
     */
    public void setMyProperty(String myProperty)
    {
        this.myProperty = myProperty;
    }

    /**
     * Get property
     */
    public String getMyProperty()
    {
        return this.myProperty;
    }

    /**
     * Custom processor
     *
     * {@sample.xml ../../../doc/Disruptor-connector.xml.sample disruptor:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     */
    @Processor
    public String myProcessor(String content)
    {
        /*
         * MESSAGE PROCESSOR CODE GOES HERE
         */

        return content;
    }
}
